//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkoutTrackerWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonDetHistory
    {
        public int IdPersonDetail { get; set; }
        public int IdPerson { get; set; }
        public Nullable<int> HeightInches { get; set; }
        public Nullable<int> WeightLbs { get; set; }
        public System.DateTime DateTime { get; set; }
    }
}
