//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkoutTrackerWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonWorkoutDetail
    {
        public int IdPersonWorkout { get; set; }
        public int IdDetailLine { get; set; }
        public int SetNumber { get; set; }
        public int Weight { get; set; }
        public int Reps { get; set; }
        public Nullable<int> Machine { get; set; }
        public int Exercise { get; set; }
    }
}
