
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WorkoutTrackerWeb.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PersonWorkoutMaster
{

    public int IdWorkout { get; set; }

    public int IdPerson { get; set; }

    public System.DateTime WorkoutDate { get; set; }

}

}
